name: Deploy Multiple Branches to GitHub Pages

on:
  push:
    branches: [main, develop, feature/*, hotfix/*]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set branch name for deployment
        id: branch
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch_name=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "branch_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build application
        run: npm run build
        env:
          PUBLIC_URL: /magic-the-tindering/${{ steps.branch.outputs.branch_name }}
          REACT_APP_BRANCH: ${{ steps.branch.outputs.branch_name }}

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-content
          fetch-depth: 0
        continue-on-error: true

      - name: Create directory structure
        run: |
          # Create gh-pages directory if it doesn't exist
          mkdir -p gh-pages-content
          
          # Create branch-specific directory
          mkdir -p "gh-pages-content/${{ steps.branch.outputs.branch_name }}"
          
          # Copy build files to branch directory
          cp -r build/* "gh-pages-content/${{ steps.branch.outputs.branch_name }}/"
          
          # If this is main branch, also copy to root
          if [ "${{ steps.branch.outputs.branch_name }}" = "main" ]; then
            cp -r build/* gh-pages-content/
          fi
          
          # Always ensure there's a root index.html for GitHub Pages to work properly
          if [ ! -f "gh-pages-content/index.html" ]; then
            echo "Creating root index.html redirecting to main branch"
            cat > gh-pages-content/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=./main/">
            <link rel="canonical" href="./main/">
            <title>Redirecting to main branch...</title>
          </head>
          <body>
            <p>Redirecting to <a href="./main/">main branch</a>...</p>
          </body>
          </html>
          EOF
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-content
          keep_files: true

      - name: Comment PR with deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const deployUrl = `https://jtrevag.github.io/magic-the-tindering/pr-${{ github.event.number }}/`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview deployment ready!**\n\n📱 **Live Preview:** ${deployUrl}\n\n*This preview will be updated automatically with new commits to this PR.*`
            });